FROM node:18 AS build

WORKDIR /app
COPY frontend/ ./frontend
WORKDIR /app/frontend

RUN npm install && npm run build

FROM nginx:alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html

# ADD THIS LINE 👇
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]